# Generated by Django 5.0.4 on 2024-04-29 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('has_leave_days', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('leave_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_name', models.CharField(max_length=255)),
                ('default_days', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'LeaveTypes',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('role', models.CharField(choices=[('EMP', 'Employee'), ('MGR', 'Manager'), ('HR', 'HR')], max_length=3)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.branch')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave.user')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('MGR', 'Approved by Manager'), ('HR', 'Approved by HR'), ('DEC', 'Declined')], default='PEN', max_length=3)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.leavetype')),
                ('hr_approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_approvals', to='leave.user')),
                ('manager_approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_approvals', to='leave.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='leave.user')),
            ],
            options={
                'db_table': 'LeaveRequests',
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeaveDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_days', models.IntegerField()),
                ('last_accrual_date', models.DateField()),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.leavetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.user')),
            ],
            options={
                'db_table': 'EmployeeLeaveDays',
                'unique_together': {('user', 'leave_type')},
            },
        ),
    ]
